// Generated by scripts/generate-speaker-music.mjs. Do not edit manually.

export const generatedSpeakerMusicTracks = {
  blindingLights: {
    label: 'Blinding Lights',
    qualities: {
      flac: {
        format: 'flac',
        path: '/audio/blinding-lights/blinding-lights.flac',
        sizeBytes: 43585284,
      },
      mp3: {
        format: 'mp3',
        path: '/audio/blinding-lights/blinding-lights.mp3',
        sizeBytes: 4705011,
      },
    },
  },
  evilManBlues: {
    label: 'Evil Man Blues',
    qualities: {
      flac: {
        format: 'flac',
        path: '/audio/evil-man-blues/evil-man-blues.flac',
        sizeBytes: 30531832,
      },
      mp3: {
        format: 'mp3',
        path: '/audio/evil-man-blues/evil-man-blues.mp3',
        sizeBytes: 6264815,
      },
    },
  },
} as const;
